language: generic

jobs:
    include:
        - os: linux
          language: python
          services:
              - docker
          script:
              - ./make/manylinux1/build_wheels.sh
        - os: osx
          osx_image: xcode9.4
          script:
              - ./make/osx/build_wheels.sh
install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then ./make/osx/install_python.sh; fi
